tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: QCYVAPH-UK58402
      user: Suvarna
      role: SYSADMIN
      database: TASTY_BYTES_DBT_DB
      warehouse: tasty_bytes_dbt_wh
      schema: raw
      password: Trial@11335599
